describe("RomanNumerals", function() {
  var roman;

  beforeEach(function() {
    roman = makeRomanNumerals();
  });

  describe("arabic to roman", function() {
    [
      { arabic: 1, numeral: 'I' },
      { arabic: 2, numeral: 'II' },
      { arabic: 3, numeral: 'III' },
      { arabic: 4, numeral: 'IV' },
      { arabic: 5, numeral: 'V' },
      { arabic: 6, numeral: 'VI' },
      { arabic: 7, numeral: 'VII' }, 
      { arabic: 8, numeral: 'VIII' },
      { arabic: 9, numeral: 'IX' },
      { arabic: 10, numeral: 'X'},
      { arabic: 11, numeral: 'XI'},
      { arabic: 12, numeral: 'XII'},
      { arabic: 13, numeral: 'XIII'},
      { arabic: 14, numeral: 'XIV'},
      { arabic: 15, numeral: 'XV'},
      { arabic: 16, numeral: 'XVI'},
      { arabic: 17, numeral: 'XVII'},
      { arabic: 18, numeral: 'XVIII'},
      { arabic: 19, numeral: 'XIX'},
      { arabic: 20, numeral: 'XX'},
      { arabic: 21, numeral: 'XXI'},
      { arabic: 22, numeral: 'XXII'},
      { arabic: 23, numeral: 'XXIII'},
      { arabic: 24, numeral: 'XXIV'},
      { arabic: 25, numeral: 'XXV'},
      { arabic: 26, numeral: 'XXVI'},
      { arabic: 27, numeral: 'XXVII'},
      { arabic: 28, numeral: 'XXVIII'},
      { arabic: 29, numeral: 'XXIX'},
      { arabic: 30, numeral: 'XXX'},
      { arabic: 31, numeral: 'XXXI'},
      { arabic: 32, numeral: 'XXXII'},
      { arabic: 33, numeral: 'XXXIII'},
      { arabic: 34, numeral: 'XXXIV'},
      { arabic: 35, numeral: 'XXXV'},
      { arabic: 36, numeral: 'XXXVI'},
      { arabic: 37, numeral: 'XXXVII'},
      { arabic: 38, numeral: 'XXXVIII'},
      { arabic: 39, numeral: 'XXXIX'},
      { arabic: 40, numeral: 'XL'},
      { arabic: 41, numeral: 'XLI'},
      { arabic: 42, numeral: 'XLII'},
      { arabic: 43, numeral: 'XLIII'},
      { arabic: 44, numeral: 'XLIV'},
      { arabic: 45, numeral: 'XLV'},
      { arabic: 46, numeral: 'XLVI'},
      { arabic: 47, numeral: 'XLVII'},
      { arabic: 48, numeral: 'XLVIII'},
      { arabic: 49, numeral: 'XLIX'},
      { arabic: 50, numeral: 'L'}, 
	  { arabic: 51, numeral: 'LI'}, 
      { arabic: 52, numeral: 'LII'}, 
   	  { arabic: 53, numeral: 'LIII'}, 
   	  { arabic: 54, numeral: 'LIV'}, 
   	  { arabic: 55, numeral: 'LV'}, 
   	  { arabic: 56, numeral: 'LVI'}, 
   	  { arabic: 57, numeral: 'LVII'}, 
   	  { arabic: 58, numeral: 'LVIII'}, 
   	  { arabic: 59, numeral: 'LIX'}, 
   	  { arabic: 60, numeral: 'LX'}, 
   	  { arabic: 61, numeral: 'LXI'}, 
   	  { arabic: 62, numeral: 'LXII'}, 
   	  { arabic: 63, numeral: 'LXIII'}, 
   	  { arabic: 64, numeral: 'LXIV'}, 
   	  { arabic: 65, numeral: 'LXV'}, 
   	  { arabic: 66, numeral: 'LXVI'}, 
   	  { arabic: 67, numeral: 'LXVII'}, 
   	  { arabic: 68, numeral: 'LXVIII'}, 
   	  { arabic: 69, numeral: 'LXIX'}, 
   	  { arabic: 70, numeral: 'LXX'}, 
   	  { arabic: 71, numeral: 'LXXI'}, 
   	  { arabic: 72, numeral: 'LXXII'}, 
   	  { arabic: 73, numeral: 'LXXIII'}, 
   	  { arabic: 74, numeral: 'LXXIV'}, 
   	  { arabic: 75, numeral: 'LXXV'}, 
   	  { arabic: 76, numeral: 'LXXVI'}, 
   	  { arabic: 77, numeral: 'LXXVII'}, 
   	  { arabic: 78, numeral: 'LXXVIII'}, 
   	  { arabic: 79, numeral: 'LXXIX'}, 
   	  { arabic: 80, numeral: 'LXXX'}, 
   	  { arabic: 81, numeral: 'LXXXI'}, 
   	  { arabic: 82, numeral: 'LXXXII'}, 
   	  { arabic: 83, numeral: 'LXXXIII'}, 
   	  { arabic: 84, numeral: 'LXXXIV'}, 
   	  { arabic: 85, numeral: 'LXXXV'}, 
   	  { arabic: 86, numeral: 'LXXXVI'}, 
   	  { arabic: 87, numeral: 'LXXXVII'}, 
   	  { arabic: 88, numeral: 'LXXXVIII'}, 
   	  { arabic: 89, numeral: 'LXXXIX'}, 
   	  { arabic: 90, numeral: 'XC'}, 
   	  { arabic: 91, numeral: 'XCI'}, 
   	  { arabic: 92, numeral: 'XCII'}, 
   	  { arabic: 93, numeral: 'XCIII'}, 
   	  { arabic: 94, numeral: 'XCIV'}, 
   	  { arabic: 95, numeral: 'XCV'}, 
   	  { arabic: 96, numeral: 'XCVI'}, 
   	  { arabic: 97, numeral: 'XCVII'}, 
   	  { arabic: 98, numeral: 'XCVIII'}, 
   	  { arabic: 99, numeral: 'XCIX'}, 
   	  { arabic: 100, numeral: 'C'}, 
   	  { arabic: 101, numeral: 'CI'}, 
   	  { arabic: 102, numeral: 'CII'}, 
   	  { arabic: 103, numeral: 'CIII'}, 
   	  { arabic: 104, numeral: 'CIV'}, 
   	  { arabic: 105, numeral: 'CV'}, 
   	  { arabic: 106, numeral: 'CVI'}, 
   	  { arabic: 107, numeral: 'CVII'}, 
   	  { arabic: 108, numeral: 'CVIII'}, 
   	  { arabic: 109, numeral: 'CIX'}, 
   	  { arabic: 110, numeral: 'CX'}, 
   	  { arabic: 111, numeral: 'CXI'}, 
   	  { arabic: 112, numeral: 'CXII'}, 
   	  { arabic: 113, numeral: 'CXIII'}, 
   	  { arabic: 114, numeral: 'CXIV'}, 
   	  { arabic: 115, numeral: 'CXV'}, 
   	  { arabic: 116, numeral: 'CXVI'}, 
   	  { arabic: 117, numeral: 'CXVII'}, 
   	  { arabic: 118, numeral: 'CXVIII'}, 
   	  { arabic: 119, numeral: 'CXIX'}, 
   	  { arabic: 120, numeral: 'CXX'}, 
   	  { arabic: 121, numeral: 'CXXI'}, 
   	  { arabic: 122, numeral: 'CXXII'}, 
   	  { arabic: 123, numeral: 'CXXIII'}, 
   	  { arabic: 124, numeral: 'CXXIV'}, 
   	  { arabic: 125, numeral: 'CXXV'}, 
   	  { arabic: 126, numeral: 'CXXVI'}, 
   	  { arabic: 127, numeral: 'CXXVII'}, 
   	  { arabic: 128, numeral: 'CXXVIII'}, 
   	  { arabic: 129, numeral: 'CXXIX'}, 
   	  { arabic: 130, numeral: 'CXXX'}, 
   	  { arabic: 140, numeral: 'CXL'}, 
   	  { arabic: 150, numeral: 'CL'}, 
   	  { arabic: 160, numeral: 'CLX'}, 
   	  { arabic: 170, numeral: 'CLXX'}, 
   	  { arabic: 180, numeral: 'CLXXX'}, 
   	  { arabic: 190, numeral: 'CXC'}, 
   	  { arabic: 200, numeral: 'CC'}, 
   	  { arabic: 300, numeral: 'CCC'}, 
   	  { arabic: 400, numeral: 'CD'}, 
   	  { arabic: 500, numeral: 'D'}, 
   	  { arabic: 600, numeral: 'DC'}, 
   	  { arabic: 700, numeral: 'DCC'}, 
   	  { arabic: 800, numeral: 'DCCC'}, 
   	  { arabic: 900, numeral: 'CM'}, 
   	  { arabic: 1000, numeral: 'M'}, 
   	  { arabic: 1100, numeral: 'MC'}, 
   	  { arabic: 1200, numeral: 'MCC'}, 
   	  { arabic: 1300, numeral: 'MCCC'}, 
   	  { arabic: 1400, numeral: 'MCD'}, 
   	  { arabic: 1500, numeral: 'MD'}, 
   	  { arabic: 1600, numeral: 'MDC'}, 
   	  { arabic: 1700, numeral: 'MDCC'}, 
   	  { arabic: 1800, numeral: 'MDCCC'}, 
   	  { arabic: 1900, numeral: 'MCM'}, 
   	  { arabic: 1934, numeral: 'MCMXXXIV'},
      { arabic: 2000, numeral: 'MM'}, 
   	  { arabic: 3000, numeral: 'MMM'}
    ].forEach(function(testRoman) {it ("should return " + testRoman.numeral + " for arabic number " + testRoman.arabic, function() {
        expect(roman.numeral(testRoman.arabic)).toBe(testRoman.numeral);
      });
    });
  });
});
